config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: { first_try: 1, success_category: 2, success_by_level: 3 }

  has_and_belongs_to_many :users

  validates :title, :rule, :image_url, :parameter, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def show
    @badge = Badge.find(params[:id])
  end

  def edit;end

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path(@badge)
    else
      render :new
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badges
    @badges = Badge.all
  end

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule, :parameter)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<div>
  <div> <h5>Название: <%= badge.title %></h5></div>
  <div>
    <p>Условие: <%= badge.rule %></p>
    <p>Параметр: <%= badge.parameter %></p>
    <%= image_tag "#{badge.image_url}", alt: "#{badge.image_url}", class: 'img-thumbnail' %>
  </div>

  <div>
    <%= link_to 'Удалить', admin_badge_path(badge),
                data: {method: :delete, confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title %>
  </p>

  <p>
    <%= form.label :rule %><br>
    <%= form.select :rule, Badge.rules.keys %>
  </p>

  <p>
    <%= form.label :parameter %>
    <%= form.text_field :parameter, placeholder: 'level/category'%>
  </p>

  <p>
    <%= form.label :image_url %>
    <%= form.text_field :image_url, placeholder: 'Image url'%>  </p>

  <p><%= form.submit %></p>

<% end %>

<%= link_to "Назад", admin_tests_path %>

app/views/admin/badges/index.html.erb
<h1>Бэйджи</h1>
<%= link_to 'Создать бэйдж', new_admin_badge_path%>
<%= render 'shared/errors', resource: @badge %>
<div>
  <%= render @badges %>
</div>
<%= link_to "Назад", admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1>Создать бэйдж</h1>

<%= render 'form' %>