config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists
  end
end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :question

  validate :validate_answers, on: :create
  validates :title, presence: true

  scope :correct, -> { where(correct: true) }

  def validate_answers
    if question.answers.count >= 4
      errors.add(:answer, "Количество ответов должно быть от 1 до 4")
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show;end

  def new
    @answer = Answer.new
  end

  def edit;end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :correct)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show;end

  def new
    @answer = Answer.new
  end

  def edit;end

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      render :new
    end
  end

  def update
    if answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td><%= answer.title %></td>
  <td><%= link_to 'Редактировать', edit_admin_answer_path(answer) %></td>
  <td>
    <%= link_to 'Удалить',
                admin_answer_path(answer),
                method: :delete,
                data: {confirm: 'Удалить ответ?'} %>
  </td>
</tr>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title, id: :answer_title %>
  </p>

  <p>
    <%= form.label :correct %>:
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Редактировать ответ</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>

<%= link_to "Назад", admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>Создать ответ</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form'%>
<%= link_to "Назад", admin_question_path(@question)%>

app/views/admin/answers/show.html.erb
<h1>Вопрос:</h1>
<p><%= @answer.question.body %></p>
<b>Ответ:</b>
<%= @answer.title %><br>
<b>Correct:</b>
<%= @answer.correct %><br>
<p>
  <%= link_to "Удалить",
  admin_answer_path(@answer),
  method: "delete",
  data: { confirm: 'Are you sure?'} %>
  <%= link_to "Назад", admin_question_path(@answer.question) %>
  <%= link_to "Редактировать", edit_admin_answer_url(@answer) %>
</p>